// generate_sitemap.js - write public/sitemap.xml from what the site actually serves.
//
// WHY THIS EXISTS
//
// The sitemap was hand-written when the archive was one document with tabbed
// views, so it listed a single URL. Routing later gave /stats, /decoder,
// /history, /tools and /legends real addresses with their own titles, and every
// /model/<KEY> its own page with a real name and record count - 40 indexable
// pages in total, of which the sitemap advertised one. A hand-maintained list
// drifts the moment a model is added or dropped, which is exactly what happened
// to models.json.
//
// So nothing here is typed by hand. The host and the view routes are read out
// of src/index.js, and the models out of public/data/models.json, which is
// itself generated from database.js. Add a model or a route and this picks it
// up; remove one and it disappears.
//
// /chassis/<NUMBER> is deliberately absent. Those are real pages too, but there
// are 1.25 million of them - far past the 50,000-URL limit for a sitemap, and
// not what a sitemap is for. They are reachable by search and by link.
//
// USAGE
//   node generate_sitemap.js          write public/sitemap.xml
//   node generate_sitemap.js --check  exit 1 if it would change, write nothing
//
// Run it after adding or removing a model or a view route.

'use strict';
const fs = require('fs');
const path = require('path');

const REPO = __dirname;
const WORKER = path.join(REPO, 'src', 'index.js');
const MODELS = path.join(REPO, 'public', 'data', 'models.json');
const OUT = path.join(REPO, 'public', 'sitemap.xml');

const worker = fs.readFileSync(WORKER, 'utf8');

// Canonical host, from the constant the worker canonicals everything to. Read
// rather than repeated so a domain change lands in one place.
const siteMatch = worker.match(/const SITE = '([^']+)'/);
if (!siteMatch) { console.error('Could not find SITE in src/index.js'); process.exit(1); }
const SITE = siteMatch[1].replace(/\/$/, '');

// View routes, from the same table the worker routes on.
const block = worker.match(/const VIEW_ROUTES = \{([\s\S]*?)\n\};/);
if (!block) { console.error('Could not find VIEW_ROUTES in src/index.js'); process.exit(1); }
const views = [...block[1].matchAll(/^\s*'([^']+)':/gm)].map(m => m[1]);
if (!views.includes('/')) { console.error('VIEW_ROUTES has no "/" entry'); process.exit(1); }

const index = JSON.parse(fs.readFileSync(MODELS, 'utf8').replace(/^﻿/, ''));
const models = Object.keys(index.models || {});
if (!models.length) { console.error('models.json lists no models'); process.exit(1); }

const today = new Date().toISOString().slice(0, 10);

// Priority says which pages matter most RELATIVE to each other on this site,
// which is all a crawler does with it. The homepage is the archive; the views
// are its main sections; a single model sits below both.
const urls = [
  { loc: SITE + '/', priority: '1.0', changefreq: 'monthly' },
  ...views.filter(v => v !== '/').sort()
      .map(v => ({ loc: SITE + v, priority: '0.8', changefreq: 'monthly' })),
  // Sorted by record count, largest first: the order is meaningless to a
  // crawler but makes the file readable, and puts the chassis most people
  // search for at the top.
  ...models.slice()
      .sort((a, b) => (index.models[b].count || 0) - (index.models[a].count || 0))
      .map(k => ({ loc: `${SITE}/model/${k}`, priority: '0.7', changefreq: 'yearly' }))
];

const body = urls.map(u =>
  '  <url>\n' +
  `    <loc>${u.loc}</loc>\n` +
  `    <lastmod>${today}</lastmod>\n` +
  `    <changefreq>${u.changefreq}</changefreq>\n` +
  `    <priority>${u.priority}</priority>\n` +
  '  </url>').join('\n');

const xml =
`<?xml version="1.0" encoding="UTF-8"?>
<!-- GENERATED by generate_sitemap.js - do not edit by hand.
     Host and view routes come from src/index.js, models from
     public/data/models.json. Re-run after adding or removing either.

     /chassis/<NUMBER> is not listed: 1.25 million URLs is well past the
     50,000 a sitemap may carry, and not what a sitemap is for. -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${body}
</urlset>
`;

if (process.argv.includes('--check')) {
  const current = fs.existsSync(OUT) ? fs.readFileSync(OUT, 'utf8') : '';
  // lastmod moves every day on its own, so compare everything else.
  const strip = (s) => s.replace(/<lastmod>[^<]*<\/lastmod>/g, '');
  if (strip(current) !== strip(xml)) {
    console.error('sitemap.xml is out of date - run: node generate_sitemap.js');
    process.exit(1);
  }
  console.log(`sitemap.xml current (${urls.length} URLs)`);
} else {
  fs.writeFileSync(OUT, xml, 'utf8');
  console.log(`Wrote ${urls.length} URLs to public/sitemap.xml`);
  console.log(`  1 homepage, ${views.length - 1} views, ${models.length} models`);
  console.log(`  host ${SITE}`);
}
