/**
 * BPZILLA — edge request handling
 *
 * Two jobs, both of which need a decision made before a static file is handed
 * over: keeping /data/ from being a bulk download, and giving the archive's
 * views real URLs with their own metadata.
 *
 * ---------------------------------------------------------------------------
 * 1. /data/ — bulk-copy protection
 * ---------------------------------------------------------------------------
 * The record files are the site. `curl https://bpzilla.com/data/fast_hcr32.json`
 * returned 144,097 records in 0.41s with no browser, no referer and no session —
 * thirty-eight of those and someone has the whole 1.40M-record archive in a few
 * seconds. robots.txt says not to, but robots.txt is a request, not a control,
 * and the crawlers worth worrying about are exactly the ones that ignore it.
 *
 * This cannot make the data uncopyable. The archive is queried in the visitor's
 * browser, so the browser must receive all of it, and anything a browser can
 * receive a headless browser can receive too. A spoofed header defeats the
 * origin check outright. What the two layers here remove is the free option:
 * copying stops being one shell command and starts needing a real browser
 * driven page by page, against a per-address limit.
 *
 * ---------------------------------------------------------------------------
 * 2. Routing — real URLs for the views
 * ---------------------------------------------------------------------------
 * The site was a single URL: every model, every record and every tab shared
 * one address, one <title> and one description. Nothing could be linked to,
 * nothing survived a refresh, and search engines had exactly one page to index.
 *
 * Hash routing would have fixed the linking but not the indexing — Google
 * stopped treating fragments as separate URLs when hashbang was deprecated.
 * Real paths need a server, which the /data/ gate had already made necessary,
 * so the two arrived together.
 *
 * Each known path is served the same index.html with its <title>, description,
 * canonical and social tags rewritten to match, from the counts in
 * data/models.json (generated by extract_models.js from database.js itself, so
 * it can't drift). The client reads location.pathname and opens the matching
 * view — see App.Router in js/app.js.
 */

const DATA_PREFIX = '/data/';

// Tab paths. Keys are what a visitor types; values are the view the client
// opens. Kept deliberately short — /decoder rather than /fast-decoder-view.
const VIEW_ROUTES = {
  '/':         { view: 'database-view',     title: null },
  '/stats':    { view: 'stats-view',        title: 'Production statistics & rarity' },
  '/decoder':  { view: 'fast-decoder-view', title: 'Factory build plate decoder' },
  '/history':  { view: 'history-view',      title: 'Skyline history' },
  '/tools':    { view: 'tools-view',        title: 'Paint index & reference tools' },
  '/legends':  { view: 'legends-view',      title: 'Silvia, 180SX, Stagea & 300ZX records' }
};

// The canonical host — what every page tells a search engine it really is.
//
// gtr-registry.org is primary: it describes the content far better than
// bpzilla does, and .org suits a registry. Flipped here only after the domain
// was confirmed serving — a canonical pointing at a host that does not resolve
// tells search engines to drop the pages that do work, so the order mattered.
//
// BOTH domains canonical here, which is the point: it makes them one site
// rather than two copies of the same 1.40M records competing with each other.
// bpzilla.com keeps working and keeps its own wordmark; it just tells search
// engines where the real address is.
const SITE = 'https://gtr-registry.org';

// Hosts that wear the GTR Registry mark instead of the BPZILLA one. Same
// worker, same assets, same records — one deployment answering to both names,
// because maintaining a second copy of a 1.36M-record archive to change a logo
// would be absurd. Everything else about the page is identical by design.
const GTR_HOSTS = new Set(['gtr-registry.org', 'www.gtr-registry.org']);

// ---------------------------------------------------------------------------
// /data/ gate
// ---------------------------------------------------------------------------

/**
 * Is this request the site's own page asking for its data?
 * Any one of three same-origin signals is accepted, because none is universal:
 * Sec-Fetch-Site is absent before Safari 16.4, and Referer can be stripped by a
 * privacy extension or a stricter referrer policy. A request with none of them —
 * which is what curl, wget and every generic crawler sends — is refused.
 */
function sameOriginSignal(request, origin) {
  if (request.headers.get('Sec-Fetch-Site') === 'same-origin') return 'sec-fetch-site';

  const referer = request.headers.get('Referer');
  if (referer) {
    try {
      if (new URL(referer).origin === origin) return 'referer';
    } catch { /* malformed Referer — treat as absent */ }
  }

  if (request.headers.get('Origin') === origin) return 'origin';
  return null;
}

function refused() {
  const body =
    'The BPZILLA factory records are served to the archive itself, not as a ' +
    'bulk download.\n\n' +
    'If you are looking at this because something you wrote stopped working: ' +
    'requests for /data/ now have to come from a page on bpzilla.com. If you ' +
    'want this data for a project, ask — contact@bpzilla.com — rather than ' +
    'scraping it. It took a long time to decode and it is given freely to ' +
    'anyone who asks.\n';

  return new Response(body, {
    status: 403,
    headers: {
      'Content-Type': 'text/plain; charset=utf-8',
      // Never let a refusal be cached and then handed to a real visitor, or
      // the reverse. This decision is per-request, not per-URL.
      'Cache-Control': 'no-store',
      'X-Content-Type-Options': 'nosniff',
      'X-Robots-Tag': 'noindex'
    }
  });
}

function tooMany() {
  return new Response(
    'Too many requests for the factory records from this address.\n\n' +
    'The archive is 38 files fetched once per page load; this limit sits well ' +
    'above that. If you need the data in bulk, ask — contact@bpzilla.com.\n',
    {
      status: 429,
      headers: {
        'Content-Type': 'text/plain; charset=utf-8',
        'Retry-After': '60',
        'Cache-Control': 'no-store',
        'X-Robots-Tag': 'noindex'
      }
    }
  );
}

/**
 * Per-IP limit on /data/, which is the half of this that a spoofed header
 * can't get around. Deliberately fails open: if the binding is missing or
 * throws, the request is allowed. A rate limiter having a bad day must never
 * be the reason the archive stops loading.
 */
async function withinRateLimit(request, env) {
  const limiter = env.DATA_RATE_LIMIT;
  if (!limiter || typeof limiter.limit !== 'function') return true;
  const key = request.headers.get('CF-Connecting-IP') || 'unknown';
  try {
    const { success } = await limiter.limit({ key });
    return success;
  } catch {
    return true;
  }
}

// ---------------------------------------------------------------------------
// Routing
// ---------------------------------------------------------------------------

let modelIndex = null;     // cached per isolate; the file is ~11 KB

async function getModels(env) {
  if (modelIndex) return modelIndex;
  try {
    const res = await env.ASSETS.fetch(new Request(`${SITE}/data/models.json`));
    if (!res.ok) return null;
    modelIndex = await res.json();
  } catch {
    modelIndex = null;
  }
  return modelIndex;
}

const esc = (s) => String(s)
  .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
  .replace(/"/g, '&quot;');

const n = (x) => Number(x || 0).toLocaleString('en-US');

/**
 * Work out what a path is about, and what its page should be called.
 * Returns null for anything that isn't a known route, which then falls through
 * to normal asset serving (and to the 404 page for genuine typos).
 */
async function describeRoute(pathname, env) {
  const decoded = decodeURIComponent(pathname).replace(/\/+$/, '') || '/';

  if (VIEW_ROUTES[decoded]) {
    const r = VIEW_ROUTES[decoded];
    if (!r.title) return null;                   // homepage keeps its own tags
    return {
      view: r.view,
      canonical: `${SITE}${decoded}`,
      title: `${r.title} | GTR Registry`,
      description:
        `${r.title} across 1,396,771 Nissan factory records read from the ` +
        `Nissan FAST microfiche — Skyline, Silvia, Stagea and 300ZX.`
    };
  }

  const model = decoded.match(/^\/model\/([A-Za-z0-9_]+)$/);
  if (model) {
    const index = await getModels(env);
    const key = model[1].toUpperCase();
    const m = index && index.models[key];
    if (!m) return null;
    return {
      view: m.legend ? 'legends-view' : 'database-view',
      model: key,
      modelName: m.name,
      count: m.count,
      years: m.years,
      engine: m.engine,
      body: m.body,
      canonical: `${SITE}/model/${key}`,
      title: `${m.name} — ${n(m.count)} factory records | GTR Registry`,
      description:
        `${n(m.count)} ${m.name} records from the Nissan FAST microfiche` +
        `${m.years ? `, built ${m.years}` : ''}. ` +
        `${m.engine ? m.engine + '. ' : ''}` +
        `Chassis numbers, build dates, factory paint codes and grade breakdowns.`
    };
  }

  const chassis = decoded.match(/^\/chassis\/([A-Za-z0-9-]{4,24})$/);
  if (chassis) {
    const id = chassis[1].toUpperCase();
    const index = await getModels(env);
    let m = null, mId = null;
    if (index) {
      // Longest stamp first, so KPS13 wins over PS13 on "KPS130-000001".
      // Entries rather than values: the key is the model id, and the
      // breadcrumb needs it to link back to /model/<id>.
      const stamps = Object.entries(index.models)
        .filter(([, x]) => x.stamp && /^[A-Z0-9]+$/.test(x.stamp))
        .sort((a, b) => b[1].stamp.length - a[1].stamp.length);
      const hit = stamps.find(([, x]) => id.startsWith(x.stamp)) || null;
      if (hit) { mId = hit[0]; m = hit[1]; }
    }
    // A chassis-shaped string whose prefix matches no chassis in the archive is
    // a typo, not a record. Answering 200 for it would be the soft 404 that
    // not_found_handling: "404-page" was chosen to avoid — every mistyped URL
    // reported to search engines as a real page. Export models are the
    // exception: their identifier is a 17-character VIN with no chassis prefix
    // to match, so those are let through.
    // Standard 17-char VIN alphabet: I, O, Q are excluded (ISO 3779) so they
    // can't be mistaken for 1, 0, 0.
    const looksLikeVin = /^[A-HJ-NPR-Z0-9]{17}$/.test(id);
    if (!m && !looksLikeVin) return null;
    return {
      view: m && m.legend ? 'legends-view' : 'database-view',
      chassis: id,
      model: mId,
      modelName: m ? m.name : null,
      canonical: `${SITE}/chassis/${id}`,
      title: m
        ? `${id} — ${m.name} factory record | GTR Registry`
        : `${id} — Nissan factory record | GTR Registry`,
      description: m
        ? `Factory record for ${id}, a ${m.name}${m.years ? ` (${m.years})` : ''}: ` +
          `build date, factory paint code, grade and decoded build plate, ` +
          `read from the Nissan FAST microfiche.`
        : `Factory record for ${id}: build date, factory paint code, grade and ` +
          `decoded build plate, read from the Nissan FAST microfiche.`
    };
  }

  return null;
}

/**
 * Per-route structured data, appended as a second JSON-LD block.
 *
 * index.html already carries a site-level graph — a WebSite node and one
 * Dataset describing the whole archive — and that graph was being served
 * byte-identical on all 1.25 million URLs. Every model page therefore told
 * Google it was the same Dataset as every other, which is the one thing
 * structured data exists to disambiguate.
 *
 * A separate block rather than a rewrite of the existing one: the site-level
 * nodes are still true on every page and are what `isPartOf` points at, and
 * more than one ld+json block per document is ordinary and well supported.
 *
 * Only what the model index actually holds is emitted. No `distribution`,
 * because /data/ answers 403 to anything without a same-site referer and
 * advertising a download that refuses to serve is worse than none.
 */
function structuredData(route) {
  const graph = [];
  const crumbs = [{ name: 'Home', item: `${SITE}/` }];

  if (route.model && route.chassis) {
    crumbs.push({ name: route.modelName || route.model, item: `${SITE}/model/${route.model}` });
    crumbs.push({ name: route.chassis, item: route.canonical });
  } else if (route.chassis) {
    crumbs.push({ name: route.chassis, item: route.canonical });
  } else if (route.model) {
    crumbs.push({ name: route.modelName || route.model, item: route.canonical });
  } else {
    crumbs.push({ name: route.title.replace(/ \| GTR Registry$/, ''), item: route.canonical });
  }

  graph.push({
    '@type': 'BreadcrumbList',
    '@id': `${route.canonical}#breadcrumb`,
    itemListElement: crumbs.map((c, i) => ({
      '@type': 'ListItem', position: i + 1, name: c.name, item: c.item
    }))
  });

  // A model page is a real subset of the archive, with its own size and its
  // own date range, so it gets its own Dataset pointing back at the whole.
  if (route.model && !route.chassis) {
    const about = [route.engine, route.body].filter(Boolean).join(' — ');
    graph.push({
      '@type': 'Dataset',
      '@id': `${route.canonical}#dataset`,
      name: `${route.modelName} — factory records`,
      description: route.description,
      url: route.canonical,
      isPartOf: { '@id': `${SITE}/#dataset` },
      ...(route.count ? { size: `${n(route.count)} factory records` } : {}),
      ...(route.years ? { temporalCoverage: String(route.years).replace(/\s*–\s*/, '/') } : {}),
      ...(about ? { about } : {}),
      variableMeasured: ['chassis number', 'build date', 'factory paint code',
                         'grade', 'factory options']
    });
  }

  return { '@context': 'https://schema.org', '@graph': graph };
}

/**
 * Serve index.html with this route's own metadata swapped in. Everything the
 * page needs to render is already client-side; what changes here is what a
 * search engine indexes and what a link preview shows.
 */
function withMetadata(response, route) {
  const title = esc(route.title);
  const desc = esc(route.description);
  const url = esc(route.canonical);

  // JSON.stringify inside a <script> has one escape that matters: a literal
  // "</script>" in any string value ends the block early. None of these values
  // can contain one today, but the guard costs a replace and removes the class
  // of bug entirely.
  const ld = JSON.stringify(structuredData(route)).replace(/<\//g, '<\\/');

  return new HTMLRewriter()
    .on('head', {
      element(el) {
        el.append(`<script type="application/ld+json">${ld}</script>`, { html: true });
      }
    })
    .on('title', { element(el) { el.setInnerContent(route.title); } })
    .on('meta[name="description"]', { element(el) { el.setAttribute('content', desc); } })
    .on('link[rel="canonical"]', { element(el) { el.setAttribute('href', url); } })
    .on('meta[property="og:title"]', { element(el) { el.setAttribute('content', title); } })
    .on('meta[property="og:description"]', { element(el) { el.setAttribute('content', desc); } })
    .on('meta[property="og:url"]', { element(el) { el.setAttribute('content', url); } })
    .on('meta[name="twitter:title"]', { element(el) { el.setAttribute('content', title); } })
    .on('meta[name="twitter:description"]', { element(el) { el.setAttribute('content', desc); } })
    .transform(response);
}

/**
 * Wear the GTR Registry mark instead of the BPZILLA one.
 *
 * Rewritten at the edge rather than swapped by script on load, so the correct
 * mark is in the HTML that arrives: a client-side swap would paint the wrong
 * logo first and visibly flip it, on every page load, forever.
 *
 * The Godzilla portrait goes with it. It is BPZILLA's mark — the site is named
 * for what the press called the R32 — and it means nothing next to a registry
 * wordmark, so it is removed rather than left as decoration. The dorsal crest
 * on the plate goes for the same reason.
 */
function withGtrBrand(response) {
  return new HTMLRewriter()
    .on('#godzilla-avatar-btn', { element(el) { el.remove(); } })
    .on('.brand-dorsal', { element(el) { el.remove(); } })
    .on('.brand-logo-badge', {
      element(el) {
        el.setAttribute('class', 'brand-logo-badge brand-gtr');
        el.setAttribute('aria-label', 'GTR Registry');
      }
    })
    // The R is the whole point of the mark, so it is its own element and takes
    // the GT-R red. aria-label above carries the readable name, which is why
    // splitting the letters up here costs nothing to a screen reader.
    .on('.plate-emblem', {
      element(el) { el.setInnerContent('GT<span class="gtr-r">R</span>', { html: true }); }
    })
    .on('.plate-tag', { element(el) { el.setInnerContent('REGISTRY'); } })
    // Tab icon. The .ico and the 32px .png are both the BPZILLA mark, so both
    // are pointed at the GTR SVG rather than one being left to win the race —
    // browsers choose among whatever icon links they are given, and leaving a
    // stale one in the list invites the wrong mark on some of them.
    .on('link[rel="icon"]', {
      element(el) {
        el.setAttribute('href', '/assets/gtr-registry-favicon.svg');
        el.setAttribute('type', 'image/svg+xml');
        el.removeAttribute('sizes');
      }
    })
    .transform(response);
}

// ---------------------------------------------------------------------------

export default {
  async fetch(request, env) {
    const url = new URL(request.url);

    if (url.pathname.startsWith(DATA_PREFIX)) {
      // Nothing here is writable, so anything that isn't a read is already wrong.
      if (request.method !== 'GET' && request.method !== 'HEAD') {
        return new Response('Method not allowed', {
          status: 405,
          headers: { Allow: 'GET, HEAD', 'Cache-Control': 'no-store' }
        });
      }
      // Origin check first: it's local and free, so a request that was never
      // going to be served doesn't spend a rate-limit call on the way out.
      if (!sameOriginSignal(request, url.origin)) return refused();
      if (!(await withinRateLimit(request, env))) return tooMany();
      return env.ASSETS.fetch(request);
    }

    const route = await describeRoute(url.pathname, env);
    if (route) {
      // Every route renders the same document; only its metadata differs.
      const page = await env.ASSETS.fetch(new Request(`${url.origin}/`, request));
      if (page.ok) {
        const res = new Response(page.body, page);
        res.headers.set('Cache-Control', 'public, max-age=300');
        // Two hosts share this document, and the response now depends on which
        // one asked. Without Vary, a cache that saw one host can serve that
        // copy to the other and put the wrong wordmark on the page.
        res.headers.set('Vary', 'Host');
        const withMeta = withMetadata(res, route);
        return GTR_HOSTS.has(url.hostname) ? withGtrBrand(withMeta) : withMeta;
      }
    }

    return env.ASSETS.fetch(request);
  }
};
